# Generated by Django 3.2.9 on 2022-05-01 11:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POLICE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rb', models.CharField(max_length=50, unique=True, verbose_name='RB')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Case',
            },
        ),
        migrations.CreateModel(
            name='CaseInvestigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='status')),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_case', to='POLICE.case')),
            ],
            options={
                'verbose_name': 'Case Investigator',
                'verbose_name_plural': 'Case Investigator',
            },
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Crime',
                'verbose_name_plural': 'Crime',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'District',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'User Position',
                'verbose_name_plural': 'User Position',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'zone',
                'verbose_name_plural': 'zone',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='District', to='POLICE.district')),
            ],
            options={
                'verbose_name': 'Police Station',
                'verbose_name_plural': 'Police Station',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_station', to='POLICE.station')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_position', to='POLICE.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Zonal', to='POLICE.zone')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'region',
            },
        ),
        migrations.CreateModel(
            name='InvestigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='status')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('case_investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_investigator', to='POLICE.caseinvestigator')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_status', to='POLICE.status')),
            ],
            options={
                'verbose_name': 'Investigation Record',
                'verbose_name_plural': 'Investigation Record',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Region', to='POLICE.region'),
        ),
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_complainant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complainant',
                'verbose_name_plural': 'Complainant',
            },
        ),
        migrations.AddField(
            model_name='caseinvestigator',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_investigator', to='POLICE.staff'),
        ),
        migrations.AddField(
            model_name='case',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainant_case', to='POLICE.complainant'),
        ),
        migrations.AddField(
            model_name='case',
            name='crime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_crime', to='POLICE.crime'),
        ),
        migrations.AddField(
            model_name='case',
            name='registerer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_registerer', to='POLICE.staff'),
        ),
    ]
